app:
  scheduler:
    enable: true
    interval: 14s
    force-check-delay: 10s

  clients:
    git-hub: https://api.github.com/repos/
    stack-overflow: https://api.stackexchange.com/2.3/questions/
    bot: http://localhost:8090

  git-hub-domain: github.com
  stack-overflow-domain: stackoverflow.com

  data_source_values:
    driver_class_name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

  authorization-git-hub-token: ${access-token}


spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
