app:
  scheduler:
    enable: true
    interval: 14s
    force-check-delay: 10s

  urls:
    git-hub-base-url: https://api.github.com/repos/
    stack-overflow-base-url: https://api.stackexchange.com/2.3/questions/

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
