app:
  scheduler:
    enable: true
    interval: 14s
    force-check-delay: 20s
  database-access-type: jooq

  clients:
    git-hub: https://api.github.com/repos/
    stack-overflow: https://api.stackexchange.com/2.3/questions/
    bot: http://localhost:8090
  git-hub-regexp:
    regexp-for-git-hub-owner: https://github\.com/(.*?)/
    regexp-for-git-hub-repo: https://github\.com/.*?/(.*)
  stack-overflow-regexp:
    regexp-for-stack-overflow-question-id: https://stackoverflow\.com/questions/(\d+)/([\w-]+)

  stack-overflow-domain: stackoverflow.com
  git-hub-domain: github.com
  git-hub-header-name: onevoker
  authorization-git-hub-token: ${access-token}
  git-hub-response-timeout: 15

  retry-settings:
    back-of-type: constant
    retry-count: 3
    step: 4s
    http-statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT, TOO_MANY_REQUESTS

  rate-limiting-settings:
    count: 4
    tokens: 4
    period: 10s

  swagger-endpoints:
    swagger: /swagger-ui
    api-docs: /v3/api-docs

  kafka:
    bootstrap-servers: localhost:9092
    topic-name: updates
  use-queue: false

  custom-metrics:
    messages-processed:
      name: messages-processed
      description: count processed messages
      tag: application

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    driver_class_name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: /metrics
  metrics:
    tags:
      application: ${spring.application.name}
