app:
  telegram-token: 6760080259:AAGUspwhpKB1cJ9Sm1qkux8Tx-HsEDStCxU
  scrapper-base-url: http://localhost:8080
  validator-regexp:
    - "https://github\\.com/[^/]+/[^/]+/?"
    - "https://stackoverflow\\.com/questions/\\d+/[^/]+/?"
    - "https://open.spotify.com/collection/tracks"
  response-timeout: 15s

  retry-settings:
    back-of-type: constant
    retry-count: 3
    step: 2s
    http-statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

  rate-limiting-settings:
    count: 1000
    tokens: 1000
    period: 4s

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
